import { createFileRoute } from '@tanstack/react-router';
import { useSuspenseQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Grid2X2, List, SlidersHorizontal, X, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { StoreLayout } from '@/components/store-layout';
import { ProductCard } from '@/components/store-ui';
import { categories, type Product } from '@/lib/store';
import { getProducts } from '@/lib/store.functions';

const productQuery={queryKey:['products'],queryFn:()=>getProducts()};
export const Route=createFileRoute('/shop')({loader:({context})=>context.queryClient.ensureQueryData(productQuery),head:()=>({meta:[{title:'Shop Gadgets | Boss Up Trades'},{name:'description',content:'Explore thoughtfully selected audio, cameras, wearables and smart home gadgets at Boss Up Trades.'},{property:'og:title',content:'Shop Gadgets | Boss Up Trades'},{property:'og:description',content:'Find your next everyday tech essential.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Shop});
function Shop(){const {data}=useSuspenseQuery(productQuery); const products=data as Product[];
 const [category,setCategory]=useState('All products'),[maxPrice,setMaxPrice]=useState(1200),[rating,setRating]=useState(0),[sort,setSort]=useState('featured'),[view,setView]=useState<'grid'|'list'>('grid'),[drawer,setDrawer]=useState(false);
 const reset=()=>{setCategory('All products');setMaxPrice(1200);setRating(0);setSort('featured')};
 const filtered=products.filter(p=>(category==='All products'||p.category===category)&&p.price<=maxPrice&&p.rating>=rating).sort((a,b)=>sort==='price-low'?a.price-b.price:sort==='price-high'?b.price-a.price:sort==='rating'?b.rating-a.rating:Number(b.featured)-Number(a.featured));
 const filters=<div className="space-y-8"><div className="flex items-center justify-between"><h2 className="text-sm font-bold uppercase tracking-widest">Filters</h2><Button variant="link" className="h-auto p-0 text-xs" onClick={reset}>Clear filters</Button></div><div className="border-t border-border pt-6"><h3 className="mb-4 text-xs font-bold uppercase tracking-widest">Category</h3><div className="space-y-3">{categories.map(cat=><label key={cat} className="flex cursor-pointer items-center gap-3 text-sm text-muted-foreground"><input type="radio" name="category" checked={category===cat} onChange={()=>setCategory(cat)} className="accent-primary"/><span className={category===cat?'font-semibold text-foreground':''}>{cat}</span></label>)}</div></div><div className="border-t border-border pt-6"><div className="mb-4 flex justify-between text-xs font-bold uppercase tracking-widest"><label htmlFor="price-range">Max price</label><span>{maxPrice===1200?'Any':`$${maxPrice}`}</span></div><input id="price-range" aria-label="Maximum price" type="range" min="50" max="1200" step="50" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))} className="w-full accent-primary"/><div className="flex justify-between text-xs text-muted-foreground"><span>$50</span><span>$1,200+</span></div></div><div className="border-t border-border pt-6"><h3 className="mb-4 text-xs font-bold uppercase tracking-widest">Minimum rating</h3><div className="space-y-3">{[0,4,4.5,4.8].map(value=><label key={value} className="flex cursor-pointer items-center gap-3 text-sm text-muted-foreground"><input type="radio" name="rating" checked={rating===value} onChange={()=>setRating(value)} className="accent-primary"/>{value===0?'All ratings':`${value}+ stars`}</label>)}</div></div><div className="border-t border-border pt-6"><label htmlFor="sort-sidebar" className="mb-3 block text-xs font-bold uppercase tracking-widest">Sort by</label><div className="relative"><select id="sort-sidebar" value={sort} onChange={e=>setSort(e.target.value)} className="w-full appearance-none border border-border bg-background px-3 py-3 pr-9 text-sm outline-none focus:border-primary"><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="rating">Top rated</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 h-4 w-4"/></div></div></div>;
 return <StoreLayout><div className="mx-auto max-w-7xl px-5 pt-10 sm:px-8 sm:pt-14 lg:px-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-accent-foreground">Explore the collection</p><div className="mt-2 border-b border-border pb-8"><h1 className="text-4xl font-bold sm:text-5xl">Shop all gadgets<span className="text-accent-foreground">.</span></h1><p className="mt-3 max-w-lg text-sm leading-relaxed text-muted-foreground">Good technology should make every day better. Find your next favorite here.</p></div><div className="grid gap-8 pt-8 lg:grid-cols-[210px_minmax(0,1fr)] lg:gap-12"><aside className="hidden lg:block">{filters}</aside><div className="min-w-0"><div className="mb-5 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b border-border pb-5"><p className="min-w-0 text-xs text-muted-foreground">Showing <span className="font-bold text-foreground">{filtered.length}</span> products</p><div className="flex shrink-0 items-center gap-2"><Button variant="outline" size="sm" className="lg:hidden" onClick={()=>setDrawer(true)}><SlidersHorizontal/> Filters</Button><div className="flex border border-border"><Button variant={view==='grid'?'secondary':'ghost'} size="icon" className="rounded-none" onClick={()=>setView('grid')} aria-label="Grid view" title="Grid view"><Grid2X2/></Button><Button variant={view==='list'?'secondary':'ghost'} size="icon" className="rounded-none" onClick={()=>setView('list')} aria-label="List view" title="List view"><List/></Button></div></div></div>{filtered.length?<div className={view==='grid'?'grid grid-cols-2 gap-x-3 gap-y-8 sm:gap-x-6 lg:grid-cols-3':'flex flex-col'}>{filtered.map(p=><ProductCard key={p.id} product={p} mode={view}/>)}</div>:<div className="py-24 text-center"><h2 className="text-xl font-bold">No matches found</h2><p className="mt-2 text-sm text-muted-foreground">Try widening your filters.</p><Button variant="outline" className="mt-5" onClick={reset}>Clear filters</Button></div>}</div></div></div>
 {drawer&&<div className="fixed inset-0 z-50 lg:hidden"><div className="absolute inset-0 bg-foreground/50" onClick={()=>setDrawer(false)}/><div role="dialog" aria-modal="true" aria-label="Shop filters" className="absolute inset-y-0 right-0 w-[min(85vw,360px)] overflow-y-auto bg-background p-6 shadow-xl"><div className="mb-5 flex justify-end"><Button variant="ghost" size="icon" onClick={()=>setDrawer(false)} aria-label="Close filters"><X/></Button></div>{filters}<Button className="mt-8 w-full" onClick={()=>setDrawer(false)}>Show {filtered.length} products</Button></div></div>}</StoreLayout>}
